#!/usr/bin/env node
/**
 * Fails if an en dash (U+2013) or em dash (U+2014) appears anywhere in the
 * source. House style is commas, full stops or colons instead.
 *
 * Only those two codepoints are checked. Hyphen-minus, minus sign, figure dash
 * and horizontal bar are all left alone.
 *
 * AGENTS.md is skipped: it is regenerated by `next dev`, so edits there are
 * recreated on the next run.
 */
import fs from "node:fs";
import path from "node:path";

// Written as escapes so this file does not trip its own check.
const EN_DASH = String.fromCharCode(0x2013);
const EM_DASH = String.fromCharCode(0x2014);

const SKIP_DIRS = new Set([
  "node_modules",
  ".next",
  ".git",
  ".vercel",
  "coverage",
]);
const SKIP_FILES = new Set(["AGENTS.md", "package-lock.json"]);
const CHECK_EXT = new Set([
  ".ts",
  ".tsx",
  ".js",
  ".jsx",
  ".mjs",
  ".cjs",
  ".css",
  ".md",
  ".json",
  ".html",
]);

const root = process.cwd();
const hits = [];

function walk(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      if (SKIP_DIRS.has(entry.name)) continue;
      walk(path.join(dir, entry.name));
      continue;
    }
    if (SKIP_FILES.has(entry.name)) continue;
    if (!CHECK_EXT.has(path.extname(entry.name))) continue;

    const full = path.join(dir, entry.name);
    const rel = path.relative(root, full).split(path.sep).join("/");
    const lines = fs.readFileSync(full, "utf8").split("\n");

    lines.forEach((line, i) => {
      for (const [char, label] of [
        [EN_DASH, "en dash"],
        [EM_DASH, "em dash"],
      ]) {
        let col = line.indexOf(char);
        while (col !== -1) {
          hits.push({ rel, line: i + 1, col: col + 1, label, text: line.trim() });
          col = line.indexOf(char, col + 1);
        }
      }
    });
  }
}

walk(root);

if (hits.length === 0) {
  console.log("check:dashes passed. No en dashes or em dashes found.");
  process.exit(0);
}

console.error(`check:dashes failed. Found ${hits.length} dash(es):\n`);
for (const h of hits) {
  console.error(`  ${h.rel}:${h.line}:${h.col}  ${h.label}`);
  console.error(`    ${h.text.slice(0, 120)}`);
}
console.error("\nUse a comma, full stop or colon instead.");
process.exit(1);
